#!/usr/bin/env python3

import os
import re

# Regex for finding/extracting base https://example.org
site_re = re.compile("https?://[^/\\s]+", re.IGNORECASE)


class Link:
    def __init__(self, link: str):
        # E.g. https://www.example.org/
        self.link = link

        # E.g. example.org/
        self.non_www = link.removeprefix("https://www.").removeprefix("https://")

        # E.g. E
        self.index_char = self.non_www[0].upper()  # e.g. E

        # Articles that have this link
        self.refs: list[str] = []

    def append_ref(self, ref: str):
        stripped = ref.removeprefix("content/").removesuffix(".md")

        if stripped not in self.refs:
            self.refs.append(stripped)


# Returns list of markdown files
def gather_files(path: str) -> list[str]:
    md_files: list[str] = []

    # Gather up all .md files
    for root, dirs, files in os.walk("content/articles/"):
        for f in files:
            # Not that one
            if not f.endswith(".md"):
                continue

            # That one
            md_files.append(f"{root}/{f}")

    md_files.sort()
    return md_files


# Returns list of links in a given markdown doc
def find_links(path: str) -> list[str]:
    with open(path, "r") as f:
        content = f.read()
        matches = site_re.findall(content)
        return [match for match in matches]


def render_links(all_links: dict[str, Link], path: str) -> None:
    # Track when we should start a new list with a header letter, e.g. A, B, C
    header_letters: dict[str, bool] = {}

    with open(path, "w") as f:
        f.write(
            """{{- /* This file is auto-generated by scripts/build-index.py and should not be manually modified. */ -}}\n"""
        )
        for _, link in sorted(all_links.items(), key=lambda item: item[1].non_www):
            if link.index_char not in header_letters:
                # Close previous list if one exists
                if len(header_letters) > 0:
                    f.write("</ul>\n")

                # Start new header
                f.write(f"<strong>{link.index_char}</strong>\n")
                f.write("<ul>\n")
                header_letters[link.index_char] = True

            # Generate ref anchors
            ref_anchors: list[str] = []
            idx: int = 1
            for ref in link.refs:
                ref_anchors.append(f"""<a href="/{ref}">{idx}</a>""")
                idx += 1

            # Write entry
            f.write(
                f"""  <li><a href="{link.link}">{link.non_www}</a> <sup>{", ".join(ref_anchors)}</sup></li>\n"""
            )

        # Close last list
        f.write("</ul>\n")


if __name__ == "__main__":
    # Gather up markdown files
    md_files = gather_files("content/articles/")

    # Create map of base URL (key) to Link object
    all_links: dict[str, Link] = {}
    for f in md_files:
        links = find_links(f)

        for link in links:
            if link not in all_links:
                all_links[link] = Link(link)
            all_links[link].append_ref(f)

    render_links(all_links, "layouts/shortcodes/link-index.html")
