#!/usr/bin/env python3

import os
import re

# Regex for finding/extracting base https://example.org
site_re = re.compile("https?://[^/\\s]+", re.IGNORECASE)


def gather_files(path: str) -> list[str]:
    md_files: list[str] = []

    # Gather up all .md files
    for root, dirs, files in os.walk("content/articles/"):
        for f in files:
            # Not that one
            if not f.endswith(".md"):
                continue

            # That one
            md_files.append(f"{root}/{f}")

    return md_files


def find_links(path: str) -> list[str]:
    with open(path, "r") as f:
        content = f.read()
        matches = site_re.findall(content)
        return [match for match in matches]


def render_links(all_links: list[str], path: str) -> None:
    with open(path, "w") as f:
        f.write(
            """{{- /* This file is auto-generated by scripts/build-index.py and should not be manually modified. */ -}}\n"""
        )
        f.write("<ul>\n")
        for link in all_links:
            f.write(f"""  <li><a href="{link}">{link}</a></li>\n""")
        f.write("</ul>\n")


if __name__ == "__main__":
    # Gather up markdown files
    md_files = gather_files("content/articles/")

    # For each one, add unique base URLs
    all_links: list[str] = []
    for f in md_files:
        links = find_links(f)
        [all_links.append(link) for link in links if link not in all_links]

    # Sort
    all_links.sort()

    # Render into link-index shortcode
    render_links(all_links, "layouts/shortcodes/link-index.html")
